name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} -t vision-ui-file-upload:latest .

      - name: Stop and Remove Previous Container
        run: |
          $container = docker ps -q -f name=vision-ui-file-upload
          if ($container) {
            docker stop vision-ui-file-upload
            docker rm vision-ui-file-upload
          }

      - name: Run New Docker Container
        run: |
          docker run --name vision-ui-file-upload --detach --publish 3004:3004 vision-ui-file-upload:latest

      - name: Cleanup Unused Images
        run: docker image prune -f
